Repository kiwicom/orbit-compose, pull requests merged in 2021-12, with the labels that each got.

#56 Design Tokens Autoupdate
  .github/tokens-updater.sh
  .github/workflows/tokens-updater.yml
  generator/build.gradle.kts
  generator/src/main/java/kiwi/orbit/compose/generator/colors/runner.kt
  generator/src/main/java/kiwi/orbit/compose/generator/icons/runner.kt
  generator/src/main/java/kiwi/orbit/compose/generator/illustrations/runner.kt
Labels: chore

#60 Typography: fix font-weight for title2 to medium
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/Typography.kt
Labels: bug

#61 Implement `Seat()` component
  catalog/src/main/java/kiwi/orbit/compose/catalog/NavGraph.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/SeatScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Seat.kt
  ui/src/main/res/values/strings.xml
Labels: feature
