Repository kiwicom/orbit-compose, pull requests merged in 2021-09, with the labels that each got.

#20 update to Compose 1.0.2 & Kotlin 1.5.21 & compile SDK 31
  CODEOWNERS
  build.gradle.kts
  catalog/build.gradle.kts
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/Main.kt
  gradle/libs.versions.toml
  icons/build.gradle.kts
  illustrations/build.gradle.kts
  ui/build.gradle.kts
Labels: chore

#21 Catalog release workflow: release version of APK to GH release
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  catalog/build.gradle.kts
  catalog/src/debug/res/values/ic_launcher_background.xml
  icons/build.gradle.kts
  illustrations/build.gradle.kts
  release/.gitignore
  release/secring.gpg.aes
  release/signing-cleanup.sh
  release/signing-pack.sh
  release/signing-unpack.sh
  release/signing.properties.aes
  release/upload.jks.aes
  ui/build.gradle.kts
Labels: chore

#22 Error state added to radio
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/Radio.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Radio.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/RadioLayout.kt
Labels: feature

#24 Autorelease to GooglePlay
  .github/workflows/release.yml
  release/.gitignore
  release/service-account.json.aes
  release/signing-cleanup.sh
  release/signing-pack.sh
  release/signing-unpack.sh
Labels: chore

#26 Content emphasis: add ProvideContentEmphasis and direct Text() & Icon() parameters
  catalog/src/main/java/kiwi/orbit/compose/catalog/components/AppBar.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Button.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Icon.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/IconButton.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Text.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/TextField.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/ContentEmphasis.kt
Labels: feature

#27 Orbit theme: setup default text style
  ui/src/main/java/kiwi/orbit/compose/ui/OrbitTheme.kt
Labels: bug

#28 radio field: fix too small padding for RadioField()
  ui/src/main/java/kiwi/orbit/compose/ui/controls/RadioField.kt
Labels: bug

#25 Colors: update to latest design tokens release
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/Colors.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Checkbox.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Radio.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Switch.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/TextField.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/ColorBuildersDark.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/ColorBuildersLight.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/tokens/ColorTokens.kt
Labels: feature

#29 switch: more precise drawing of Thumb
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/SwitchScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Switch.kt
Labels: bug

#30 badge: lighter border for subtle version
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Badge.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ThemedSurface.kt
Labels: bug

#31 release: put GitHub URL to release notes
  .github/workflows/release.yml
Labels: chore

#32 properly setup tooling & toolingPreview deps & fix preview crash in ui
  catalog/build.gradle.kts
  gradle/libs.versions.toml
  icons/build.gradle.kts
  illustrations/build.gradle.kts
  ui/build.gradle.kts
Labels: chore

#34 Expose color theming via `ProvideColors()` composable
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ButtonScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/OrbitTheme.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/Colors.kt
Labels: feature

#33 Checkbox error state
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/CheckboxScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Checkbox.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/CheckboxField.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Radio.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/RadioField.kt
Labels: feature

#35 radio|checkbox: sync isError parameter name with MDC
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/CheckboxScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/RadioScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Checkbox.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/CheckboxField.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Radio.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/RadioField.kt
Labels: bug

#36 cards/surface: allow to change border without loosing ripple effect
  catalog/src/main/java/kiwi/orbit/compose/catalog/NavGraph.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/CardsScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Card.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Surface.kt
Labels: bug
