Repository kiwicom/orbit-compose, pull requests merged in 2021-11, with the labels that each got.

#45 Introduce TopAppBar component
  catalog/src/main/java/kiwi/orbit/compose/catalog/Screen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/components/AppBar.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
  ui/build.gradle.kts
  ui/src/main/java/kiwi/orbit/compose/ui/controls/TopAppBar.kt
  ui/src/main/res/drawable/ic_appbar_arrow_left.xml
  ui/src/main/res/drawable/ic_appbar_arrow_right.xml
  ui/src/main/res/values/strings.xml
Labels: feature

#46 Theming: add MaterialTheme support
  catalog/build.gradle.kts
  catalog/src/main/java/kiwi/orbit/compose/catalog/NavGraph.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/DialogsMaterialDialog.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/DialogsScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/OrbitTheme.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/Colors.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/Shapes.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/Typography.kt
Labels: feature

#40 update to Compose 1.1 beta
  gradle/libs.versions.toml
Labels: feature, chore

#41 checkbox: animated checkbox mark
  gradle/libs.versions.toml
  ui/build.gradle.kts
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Checkbox.kt
  ui/src/main/res/drawable/avd_check.xml
Labels: feature

#48 TextField refactoring
  ui/src/main/java/kiwi/orbit/compose/ui/controls/TextField.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/field/FieldContent.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/field/FieldLabel.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/field/FieldMessage.kt
Labels: chore

#47 Add TextSelection coloring & introduce MaterialIsland wrapper
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/DialogsMaterialDialog.kt
  ui/src/main/java/kiwi/orbit/compose/ui/OrbitTheme.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/Islands.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/TextSelectionColors.kt
Labels: feature

#42 alerts: update button size
  ui/src/main/java/kiwi/orbit/compose/ui/OrbitTheme.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Alert.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Button.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ThemedSurface.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/AlertScope.kt
Labels: feature

#50 text field: present info message only when focused
  ui/src/main/java/kiwi/orbit/compose/ui/controls/TextField.kt
Labels: bug

#51 badge: correct icon sizing and padding
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/BadgeScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Badge.kt
Labels: bug

#52 Unify `LocalTextStyle` & `LocalContentColor` with Material
  .idea/scopes/ComposeMaterial.xml
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/DialogsMaterialDialog.kt
  ui/src/main/java/kiwi/orbit/compose/ui/OrbitTheme.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/ContentColor.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/Islands.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/TextStyle.kt
Labels: feature

#53 TextField sizing supporting smaller & intrinsic sizes
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TextFieldScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/TextField.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/field/FieldContent.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/field/FieldIcon.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/field/FieldMessage.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/internal/ColumnWithMinConstraints.kt
Labels: feature

#54 Tag: add modifier argument
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TagScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Tag.kt
Labels: feature

#44 Add `SelectField()` & `ClickableField()` controls
  catalog/build.gradle.kts
  catalog/src/main/AndroidManifest.xml
  catalog/src/main/java/kiwi/orbit/compose/catalog/NavGraph.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/SelectFieldScreen.kt
  gradle/libs.versions.toml
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ClickableField.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/SelectField.kt
Labels: feature
