Repository kiwicom/orbit-compose, pull requests merged in 2022-01, with the labels that each got.

#64 Add the `SeatLegend()` component
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/SeatScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/SeatLegend.kt
Labels: feature

#63 Adjust `Seat()` according to Orbit Native Components
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/SeatScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Seat.kt
Labels: bug

#68 Alerts - update relevant icons
  catalog/src/main/java/kiwi/orbit/compose/catalog/NavGraph.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/XProfileScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Alert.kt
Labels: feature

#67 Add `ChoiceTile()` component
  catalog/src/main/java/kiwi/orbit/compose/catalog/NavGraph.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/components/CustomPlaceholder.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ChoiceTileScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ChoiceTile.kt
Labels: feature

#70 Add `Toast()` and `Scaffold()` component
  catalog/src/main/java/kiwi/orbit/compose/catalog/NavGraph.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/Screen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ToastScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Scaffold.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Toast.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ToastHost.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/ContentColor.kt
Labels: feature

#71 update to Compose 1.1.0-RC3 & Kotlin 1.6.10
  build.gradle.kts
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Checkbox.kt
Labels: chore
