Repository kiwicom/orbit-compose, pull requests merged in 2022-06, with the labels that each got.

#161 Implement `KeyValue` and `KeyValueLarge` components
  catalog/src/main/java/kiwi/orbit/compose/catalog/NavGraph.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/KeyValueScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
  component-status.yaml
  ui/screenshots/debug/kiwi.orbit.compose.ui.ScreenshotTest_keyValue.png
  ui/src/androidTest/kotlin/kiwi/orbit/compose/ui/ScreenshotTest.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/KeyValue.kt
Labels: feature, new component

#168 Fix `BargeCircle` rounding for 10+ values
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/BadgeScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/BadgeCircle.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_badgeCircle.png
Labels: bug

#172 Implement Elevation levels
  catalog/src/main/java/kiwi/orbit/compose/catalog/Screen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/AlertScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/OrbitTheme.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Card.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Surface.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Toast.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/TopAppBar.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/ElevationLevels.kt
Labels: feature

#170 Compose 1.2
  build.gradle.kts
  catalog/build.gradle.kts
  catalog/src/main/java/kiwi/orbit/compose/catalog/CatalogApplication.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/Screen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/AlertScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/BadgeScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ButtonScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/CardsScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/CheckboxScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ChoiceTileScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ColorsScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/DialogsScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/EmptyStateScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/IconsScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/IllustrationsScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/KeyValueScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/LinearProgressIndicatorScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ListChoiceScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/LoadingScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/RadioScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/SeatScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/SelectFieldScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/StepperScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/SwitchScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TagScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TextFieldScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ToastScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TypographyScreen.kt
  generator/src/main/java/kiwi/orbit/compose/generator/illustrations/IllustrationsGenerator.kt
  gradle/libs.versions.toml
  readme.md
  ui/build.gradle.kts
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Scaffold.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/TextField.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/TopAppBar.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/TopAppBarLarge.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/internal/MutablePaddingValues.kt
Labels: feature, compose 1.2

#178 make Toast timeouts aware about animation duration scale
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Toast.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ToastHost.kt
  ui/src/main/java/kiwi/orbit/compose/ui/utils/DurationScale.kt
Labels: feature, compose 1.2

#180 update to Compose 1.2.0-rc03
  catalog/build.gradle.kts
  gradle/libs.versions.toml
  icons/build.gradle.kts
  illustrations/build.gradle.kts
  ui/build.gradle.kts
Labels: chore

#181 make Toast disappear with disabled animations
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ToastHost.kt
Labels: bug, skip-changelog

#182 Kotlin 1.7 and Compose compiler 1.2.0
  .editorconfig
  build.gradle.kts
  catalog/build.gradle.kts
  generator/build.gradle.kts
  generator/src/main/java/kiwi/orbit/compose/generator/colors/Main.kt
  generator/src/main/java/kiwi/orbit/compose/generator/icons/Main.kt
  generator/src/main/java/kiwi/orbit/compose/generator/illustrations/Main.kt
  gradle/libs.versions.toml
  icons/build.gradle.kts
  illustrations/build.gradle.kts
  ui/build.gradle.kts
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/ColorBundleGradient.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/TextSelectionColors.kt
  ui/src/main/java/kiwi/orbit/compose/ui/layout/ExpandModifier.kt
  ui/src/main/java/kiwi/orbit/compose/ui/utils/PaddingValuesExtensions.kt
Labels: chore
