Repository kiwicom/orbit-compose, pull requests merged in 2022-07, with the labels that each got.

#187 update to latest AGP 7.2.1, Gradle 7.5 and others
  build.gradle.kts
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: chore

#186 Implement Tag's active state separately from remove action
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TagScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Tag.kt
  ui/src/main/res/values/strings.xml
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_tag.png
Labels: feature

#185 Add `BadgePrimitive()` and new Bundle badge variants
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/BadgeScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Badge.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/BadgePrimitive.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_badge.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_listChoice.png
Labels: feature

#195 Better dark mode support
  catalog/src/main/java/kiwi/orbit/compose/catalog/AppTheme.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/CatalogApplication.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/BadgeScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Alert.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/AlertInline.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Badge.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/BadgeCircle.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/BadgePrimitive.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Surface.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ThemedSurface.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/ColorBuildersDark.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/ColorBuildersLight.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/ColorTransformers.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/Colors.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/ContentColor.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/LocalSmallButtonScope.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_alertCritical.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_alertInfo.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_alertSuccess.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_alertWarning.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_card.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_choiceTile.png
Labels: feature

#194 Expanded readme file
  contributing.md
  docs/readme/button_and_alert.png
  docs/readme/styled_text.png
  readme.md
Labels: chore

#197 Implement `LinearIndeterminateProgressIndicator()` component
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/LinearProgressIndicatorScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/LinearIndeterminateProgressIndicator.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/LinearProgressIndicator.kt
  ui/src/test/kotlin/ScreenshotTest.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_linearIndeterminateProgressIndicator.png
Labels: feature

#198 introduce custom lint checks for correct Orbit composables usage
  .github/workflows/build.yml
  catalog/build.gradle.kts
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/DialogsMaterialDialog.kt
  gradle/libs.versions.toml
  lint/.gitignore
  lint/build.gradle.kts
  lint/src/main/kotlin/kiwi/orbit/compose/lint/OrbitComposeIssueRegistry.kt
  lint/src/main/kotlin/kiwi/orbit/compose/lint/detectors/MaterialDesignInsteadOrbitDesignDetector.kt
  lint/src/main/resources/META-INF/services/com.android.tools.lint.client.api.IssueRegistry
  lint/src/test/kotlin/kiwi/orbit/compose/lint/detectors/MaterialDesignInsteadOrbitDesignDetectorTest.kt
  settings.gradle.kts
Labels: feature

#202 Reset ContentEmphasis with Surface composable
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Surface.kt
Labels: bug

#201 Implement `PillButton()` component
  .idea/dictionaries/shared.xml
  catalog/src/main/java/kiwi/orbit/compose/catalog/NavGraph.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/PillButtonScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/PillButton.kt
  ui/src/test/kotlin/ScreenshotTest.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_pillButton.png
Labels: feature

#204 update to AGP 7.3 to avoid dokka classpath issues
  catalog/build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: skip-changelog
