Repository kiwicom/orbit-compose, pull requests merged in 2022-12, with the labels that each got.

#290 Add `BadgeList` component
  catalog/src/main/java/kiwi/orbit/compose/catalog/CatalogApplication.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/Destinations.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/BadgeListScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
  component-status.yaml
  ui/src/main/java/kiwi/orbit/compose/ui/controls/BadgeList.kt
  ui/src/test/kotlin/ScreenshotTest.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_badgeList.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_badgeList_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_badgeList_dark.png
Labels: feature, new component

#176 Add RTL automirroring to arrow-like icons
  catalog/build.gradle.kts
  catalog/proguard-rules.pro
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/IconsScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ListChoiceScreen.kt
  generator/src/main/java/kiwi/orbit/compose/generator/icons/IconsGenerator.kt
  icons/src/main/java/kiwi/orbit/compose/icons/ColoredIcons.kt
  icons/src/main/java/kiwi/orbit/compose/icons/Icons.kt
  icons/src/main/res/drawable/ic_orbit_chevron_backward.xml
  icons/src/main/res/drawable/ic_orbit_chevron_double_backward.xml
  icons/src/main/res/drawable/ic_orbit_chevron_double_forward.xml
  icons/src/main/res/drawable/ic_orbit_chevron_forward.xml
  icons/src/main/res/drawable/ic_orbit_flight_direct.xml
  icons/src/main/res/drawable/ic_orbit_flight_multicity.xml
  icons/src/main/res/drawable/ic_orbit_flight_nomad.xml
  icons/src/main/res/drawable/ic_orbit_flight_return.xml
  icons/src/main/res/drawable/ic_orbit_route_no_stops.xml
  icons/src/main/res/drawable/ic_orbit_route_one_stop.xml
  icons/src/main/res/drawable/ic_orbit_route_two_stops.xml
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ListChoice.kt
Labels: feature, compose 1.2

#277 Add `Timeline` component
  catalog/src/main/java/kiwi/orbit/compose/catalog/CatalogApplication.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/Destinations.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TimelineScreen.kt
  component-status.yaml
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Timeline.kt
  ui/src/test/kotlin/ScreenshotTest.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_timeline.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_timelineStates.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_timelineStates_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_timelineStates_dark.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_timeline_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_timeline_dark.png
Labels: feature, new component

#297 Added a version of ListChoice that is not clickable.
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ListChoiceScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ListChoice.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_listChoice.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_listChoice_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_listChoice_dark.png
Labels: feature

#299 Update BadgeList item naming and icon colors
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/BadgeListScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/BadgeList.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_badgeList.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_badgeList_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_badgeList_dark.png
Labels: bug

#302 Expose MutableInteractionSource for buttons and other components. BC break!
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Button.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ButtonLink.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/CheckboxField.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ChoiceTile.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ChoiceTileCentered.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ClickableField.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/PillButton.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/RadioField.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/SelectField.kt
Labels: feature

#304 Fix `ClickableField` singleLine rendering
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ClickableField.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_clickableField.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_clickableField_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_clickableField_dark.png
Labels: bug, semver:patch
