Repository kiwicom/orbit-compose, pull requests merged in 2022-09, with the labels that each got.

#233 Implement `Dialog()` component
  catalog/src/main/java/kiwi/orbit/compose/catalog/NavGraph.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/DialogsOrbitDialog.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/DialogsScreen.kt
  component-status.yaml
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Dialog.kt
  ui/src/test/kotlin/ScreenshotTest.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_dialog.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_dialog_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_dialog_dark.png
Labels: feature, new component

#235 Integrated Navigation Compose Typed library
  .idea/inspectionProfiles/Project_Default.xml
  catalog/build.gradle.kts
  catalog/src/main/java/kiwi/orbit/compose/catalog/CatalogApplication.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/Destinations.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/NavGraph.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/AlertScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/BadgeScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ButtonScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/CardsScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/CheckboxScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ChoiceTileScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ColorsScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/DialogsMaterialDialog.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/DialogsScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/EmptyStateScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/IconsScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/IllustrationsScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/KeyValueScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/LinearProgressIndicatorScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ListChoiceScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ListScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/LoadingScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/PillButtonScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/RadioScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/SeatScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/SegmentedSwitchScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/SelectFieldScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/StepperScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/SwitchScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TagScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TextFieldScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ToastScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TopAppBarScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TypographyScreen.kt
  gradle/libs.versions.toml
Labels: chore

#236 Add strength indicator support in `PasswordTextField`
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TextFieldScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/PasswordStrengthIndicator.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/PasswordTextField.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/TextField.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_passwordTextField.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_passwordTextField_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_passwordTextField_dark.png
Labels: feature

#243 update to NavigationComposeTyped 0.4
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/DialogsScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TopAppBarScreen.kt
  gradle/libs.versions.toml
Labels: chore

#244 update to AGP 7.3.0
  gradle/libs.versions.toml
Labels: chore

#250 Scaffold: fix insets handling, introduce actionLayout and render action's gradient above the action
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Scaffold.kt
  ui/src/test/kotlin/ScreenshotTest.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_scaffold.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_scaffold_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_scaffold_dark.png
Labels: feature

#216 Android 13 / SDK 33
  build.gradle.kts
  catalog/build.gradle.kts
  catalog/src/main/AndroidManifest.xml
  catalog/src/main/java/kiwi/orbit/compose/catalog/AppTheme.kt
  gradle/libs.versions.toml
  settings.gradle.kts
  ui/src/test/kotlin/ScreenshotTest.kt
Labels: chore
