Repository kiwicom/orbit-compose, pull requests merged in 2022-05, with the labels that each got.

#137 badges: rename to unify & match Orbit Neutral
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/BadgeScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ChoiceTileScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Badge.kt
Labels: bug

#143 Add `InlineLoading()` component
  catalog/src/main/java/kiwi/orbit/compose/catalog/NavGraph.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/LoadingScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/InlineLoading.kt
Labels: feature, new component

#144 update to SDK 32, AGP 7.2, Coil 2.0 and others
  catalog/build.gradle.kts
  catalog/lint-baseline.xml
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TopAppBarScreensLarge.kt
  gradle/libs.versions.toml
  icons/lint-baseline.xml
  ui/src/main/java/kiwi/orbit/compose/ui/controls/CountryFlag.kt
Labels: chore

#139 Colors update
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/AlertScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ButtonScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/CardsScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ColorsScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TopAppBarScreensNormal.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Alert.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/AlertInline.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Badge.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Button.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ButtonLink.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Checkbox.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ChoiceTile.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ChoiceTileCentered.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ClickableField.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/LinearProgressIndicator.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Radio.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Seat.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Switch.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Tag.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/TextField.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ThemedSurface.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/field/FieldMessage.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/ColorBuildersDark.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/ColorBuildersLight.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/ColorTransformers.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/Colors.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/ContentColor.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/ContentEmphasis.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/TextSelectionColors.kt
Labels: feature

#150 LinearProgressBar: renamed arguments & fix RTL
  ui/src/main/java/kiwi/orbit/compose/ui/controls/LinearProgressIndicator.kt
Labels: bug

#151 Implement `ListChoice()` component
  catalog/src/main/java/kiwi/orbit/compose/catalog/NavGraph.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ListChoiceScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
  component-status.yaml
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ButtonPrimitive.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ListChoice.kt
Labels: feature, new component

#153 Update Stepper to rounded buttons design
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/StepperScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Stepper.kt
Labels: feature
