Repository kiwicom/orbit-compose, pull requests merged in 2022-08, with the labels that each got.

#210 Add missing `DeviceMobile` icon
  generator/src/main/java/kiwi/orbit/compose/generator/icons/IconsGenerator.kt
  icons/src/main/java/kiwi/orbit/compose/icons/Icons.kt
  icons/src/main/res/drawable/ic_orbit_device_mobile.xml
Labels: feature

#211 fix lint publication in :ui package
  catalog/build.gradle.kts
  ui/build.gradle.kts
Labels: bug, semver:patch

#219 Implement `SegmentedSwitch()` component
  catalog/src/main/java/kiwi/orbit/compose/catalog/NavGraph.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/SegmentedSwitchScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/SegmentedSwitch.kt
  ui/src/test/kotlin/ScreenshotTest.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_segmentedSwitch.png
Labels: feature

#221 unify plugins definition & update to AGP 7.3.0-rc01
  build.gradle.kts
  catalog/build.gradle.kts
  generator/build.gradle.kts
  gradle/libs.versions.toml
  icons/build.gradle.kts
  illustrations/build.gradle.kts
  lint/build.gradle.kts
  ui/build.gradle.kts
Labels: chore

#222 Implement `List()` component
  catalog/src/main/java/kiwi/orbit/compose/catalog/NavGraph.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ListScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
  component-status.yaml
  ui/src/main/java/kiwi/orbit/compose/ui/controls/List.kt
  ui/src/test/kotlin/ScreenshotTest.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_list.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_listLarge.png
Labels: feature

#224 Catalog unification
  catalog/build.gradle.kts
  catalog/src/main/AndroidManifest.xml
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/DialogsScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/LinearProgressIndicatorScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ListChoiceScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/PillButtonScreen.kt
  icons/build.gradle.kts
  icons/src/main/AndroidManifest.xml
  illustrations/build.gradle.kts
  illustrations/src/main/AndroidManifest.xml
  ui/build.gradle.kts
  ui/src/main/AndroidManifest.xml
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ListChoice.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_listChoice.png
Labels: chore
