Repository kiwicom/orbit-compose, pull requests merged in 2023-06, with the labels that each got.

#446 Text Field label & message moved to decoration box (BC break!)
  ui/build.gradle.kts
  ui/src/main/java/kiwi/orbit/compose/ui/controls/TextField.kt
  ui/src/test/kotlin/kiwi/orbit/compose/ui/controls/TextFieldTest.kt
Labels: feature

#452 Fix SegmentedSwitch rendering in RTL
  ui/src/main/java/kiwi/orbit/compose/ui/controls/SegmentedSwitch.kt
Labels: bug

#448 Add TileGroup
  catalog/src/main/java/kiwi/orbit/compose/catalog/CatalogApplication.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/Destinations.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TileGroupScreen.kt
  component-status.yaml
  docs/03-components/02-structure/tilegroup.mdx
  docs/readme.md
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Tile.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/TileGroup.kt
  ui/src/test/kotlin/kiwi/orbit/compose/ui/ScreenshotTest.kt
  ui/src/test/kotlin/kiwi/orbit/compose/ui/controls/TileGroupTest.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_tileGroup.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_tileGroup_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_tileGroup_dark.png
Labels: feature, new component

#450 Add capability to define default icon color for entire `List`
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ListScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/List.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_list.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_listLarge.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_listLarge_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_listLarge_dark.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_list_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_list_dark.png
Labels: feature

#454 Add CircularProgressIndicator wrapper
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/LoadingScreen.kt
  docs/03-components/10-progress-indicators/loading.mdx
  ui/src/main/java/kiwi/orbit/compose/ui/controls/CircularProgressIndicator.kt
  ui/src/test/kotlin/kiwi/orbit/compose/ui/ScreenshotTest.kt
  ui/src/test/kotlin/kiwi/orbit/compose/ui/controls/CircularProgressIndicatorTest.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_circularProgressIndicator.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_circularProgressIndicator_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_circularProgressIndicator_dark.png
Labels: feature, new component

#459 Fix font scaling issues in `Tag`, `RadioField` and `CheckboxField`
  ui/src/main/java/kiwi/orbit/compose/ui/controls/CheckboxField.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/RadioField.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Tag.kt
  ui/src/main/java/kiwi/orbit/compose/ui/layout/AlignByLineHeightModifier.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_checkboxField_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_radioField_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_tag.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_tag_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_tag_dark.png
Labels: bug, accessibility

#458 Implement top-node semantics for `Stepper` (BC break!)
  docs/03-components/07-interaction/stepper.mdx
  docs/readme.md
  ui/build.gradle.kts
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Stepper.kt
  ui/src/test/kotlin/kiwi/orbit/compose/ui/controls/StepperTest.kt
Labels: bug, accessibility

#461 Add Material/M3's CircularProgressIndicator lint detector
  lint/src/main/kotlin/kiwi/orbit/compose/lint/detectors/MaterialDesignInsteadOrbitDesignDetector.kt
Labels: feature, semver:patch

#464 Avoid Intrinsic measuring in Tile as it has problems with Image
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TileScreen.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/TileGroup.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_tile.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_tileGroup_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_tile_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_tile_dark.png
Labels: bug, semver:patch

#468 Make Alert buttons less rounded
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Alert.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Button.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/LocalRoundedContainerScope.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_alertCritical.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_alertCritical_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_alertCritical_dark.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_alertInfo.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_alertInfo_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_alertInfo_dark.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_alertSimple.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_alertSimple_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_alertSimple_dark.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_alertSuccess.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_alertSuccess_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_alertSuccess_dark.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_alertWarning.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_alertWarning_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_alertWarning_dark.png
Labels: bug

#474 Fix `Tile` width calculation when contraints.width is 0 or smaller then the trailing icon width
  ui/src/main/java/kiwi/orbit/compose/ui/controls/TileGroup.kt
Labels: bug

#473 Apply default width for TileGroup if it is empty
  ui/src/main/java/kiwi/orbit/compose/ui/controls/TileGroup.kt
Labels: bug

#475 Timeline: fix going to success from past critical/warning
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Timeline.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_timelineStates.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_timelineStates_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_timelineStates_dark.png
Labels: bug
