Repository kiwicom/orbit-compose, pull requests merged in 2023-09, with the labels that each got.

#520 Remove deprecated `ChoiceTileCentered`
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ChoiceTileScreen.kt
  ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/ChoiceTileCentered.kt
  ui/src/androidUnitTest/kotlin/kiwi/orbit/compose/ui/ScreenshotTest.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_choiceTileCentered.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_choiceTileCentered_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_choiceTileCentered_dark.png
Labels: semver:minor

#522 Introduce LabelLastBaseLine for field vertical aligment
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TextFieldScreen.kt
  docs/03-components/05-input/inputfield.mdx
  ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/TextField.kt
  ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/field/FieldLabel.kt
Labels: feature

#523 Utilize more dark color for text selection
  ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/foundation/TextSelectionColors.kt
Labels: bug

#534 Rework `Scaffold` to avoid Subcompose & fix insets consumption
  ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/Scaffold.kt
Labels: bug, feature

#535 Add lint for Orbit buttons usage within Material's AlertDialog
  lint/src/main/kotlin/kiwi/orbit/compose/lint/OrbitComposeIssueRegistry.kt
  lint/src/main/kotlin/kiwi/orbit/compose/lint/detectors/MaterialDialogWithOrbitButtonsDetector.kt
  lint/src/test/kotlin/kiwi/orbit/compose/lint/detectors/MaterialDialogWithOrbitButtonsDetectorTest.kt
Labels: feature, semver:minor

#533 Expose `EditableText` on ClickableField
  ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/ClickableField.kt
  ui/src/androidUnitTest/kotlin/kiwi/orbit/compose/ui/controls/ClickableFieldTest.kt
Labels: feature

#542 Allow usage of material TextButton inside of Material AlertDialog without lint reporting the usage.
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/DialogsMaterialDialog.kt
  lint/src/main/kotlin/kiwi/orbit/compose/lint/detectors/MaterialDesignInsteadOrbitDesignDetector.kt
  lint/src/test/kotlin/kiwi/orbit/compose/lint/detectors/MaterialDesignInsteadOrbitDesignDetectorTest.kt
Labels: feature

#545 Add a warning when a button is used inside of AlertDialog's content slot instead of actions slot
  lint/src/main/kotlin/kiwi/orbit/compose/lint/OrbitComposeIssueRegistry.kt
  lint/src/main/kotlin/kiwi/orbit/compose/lint/detectors/DialogButtonsInContentSlotDetector.kt
  lint/src/main/kotlin/kiwi/orbit/compose/lint/detectors/LintUtils.kt
  lint/src/main/kotlin/kiwi/orbit/compose/lint/detectors/MaterialDesignInsteadOrbitDesignDetector.kt
  lint/src/main/kotlin/kiwi/orbit/compose/lint/detectors/MaterialDialogWithOrbitButtonsDetector.kt
  lint/src/main/kotlin/kiwi/orbit/compose/lint/detectors/ScaffoldContentPaddingDetector.kt
  lint/src/test/kotlin/kiwi/orbit/compose/lint/detectors/DialogButtonsInContentSlotDetectorTest.kt
Labels: feature, semver:minor

#546 scaffold: be more explicit about alignment line check
  ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/Scaffold.kt
Labels: chore

#544 Add `Coupon` component
  baselineprofile/src/main/kotlin/kiwi/orbit/baselineprofile/BaselineProfileGenerator.kt
  catalog/semantics/src/main/kotlin/kiwi/orbit/compose/catalog/semantics/MainScreenSemantics.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/CatalogApplication.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/Destinations.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/CouponScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
  component-status.yaml
  docs/03-components/08-visuals/coupon.md
  ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/Coupon.kt
  ui/src/androidUnitTest/kotlin/kiwi/orbit/compose/ui/ScreenshotTest.kt
  ui/src/androidUnitTest/kotlin/kiwi/orbit/compose/ui/controls/CouponTest.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_coupon.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_coupon_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_coupon_dark.png
Labels: feature, new component
