Repository kiwicom/orbit-compose, pull requests merged in 2023-03, with the labels that each got.

#359 Update to Compose 1.4
  catalog/build.gradle.kts
  catalog/src/main/java/kiwi/orbit/compose/catalog/CatalogApplication.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/Destinations.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/DialogMaterialDatePicker.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/DialogMaterialTimePicker.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/DialogsScreen.kt
  gradle/libs.versions.toml
  icons/build.gradle.kts
  illustrations/build.gradle.kts
  readme.md
  ui/build.gradle.kts
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ClickableField.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/LinearIndeterminateProgressIndicator.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/LinearProgressIndicator.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/PasswordTextField.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/PillButton.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/SegmentedSwitch.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/SelectField.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Slider.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Surface.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Text.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/TextField.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_linearIndeterminateProgressIndicator.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_linearIndeterminateProgressIndicator_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_linearIndeterminateProgressIndicator_dark.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_linearProgressIndicator.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_linearProgressIndicator_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_linearProgressIndicator_dark.png
Labels: feature, compose 1.4

#361 Add Slack's compose lint rules
  catalog/build.gradle.kts
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/DialogMaterialTimePicker.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/IconsScreen.kt
  gradle/libs.versions.toml
  ui/build.gradle.kts
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Alert.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/AlertInline.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Badge.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/BadgeCircle.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Button.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ButtonLink.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ClickableField.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/List.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/ListChoice.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/PasswordTextField.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/PillButton.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Scaffold.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Seat.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/SeatLegend.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/SelectField.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Stepper.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/TextField.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Timeline.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/TopAppBar.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/TopAppBarLarge.kt
Labels: chore

#374 Catalog: Migrate to Compose Pager
  catalog/build.gradle.kts
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/AlertScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ButtonScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TabsScreen.kt
  gradle/libs.versions.toml
Labels: semver:patch, chore

#379 Add a modifier to the Orbit Dialog.
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Dialog.kt
Labels: bug, accessibility

#380 Add back LinearProgressIndicator's animation
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/LinearProgressIndicatorScreen.kt
  docs/03-components/10-progress-indicators/loading.mdx
  docs/readme.md
  ui/src/main/java/kiwi/orbit/compose/ui/controls/LinearProgressIndicator.kt
  ui/src/test/kotlin/kiwi/orbit/compose/ui/controls/LinearProgressIndicatorTest.kt
Labels: feature, semver:patch

#382 Add `RangeSlider`
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/SliderScreen.kt
  docs/03-components/07-interaction/slider.mdx
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Slider.kt
  ui/src/test/kotlin/kiwi/orbit/compose/ui/ScreenshotTest.kt
  ui/src/test/kotlin/kiwi/orbit/compose/ui/controls/SliderTest.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_sliderRange.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_sliderRange_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_sliderRange_dark.png
Labels: feature, new component

#386 update to stable Compose 1.4, Accompanist 0.30
  gradle/libs.versions.toml
Labels: chore

#381 Add `Collapse` Component
  catalog/src/main/java/kiwi/orbit/compose/catalog/CatalogApplication.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/Destinations.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/CollapseScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
  component-status.yaml
  docs/03-components/07-interaction/collapse.mdx
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Collapse.kt
  ui/src/test/kotlin/kiwi/orbit/compose/ui/ScreenshotTest.kt
  ui/src/test/kotlin/kiwi/orbit/compose/ui/controls/CollapseTest.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_collapse.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_collapse_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_collapse_dark.png
Labels: feature, new component
