Repository kiwicom/orbit-compose, pull requests merged in 2023-07, with the labels that each got.

#476 Docs: add new component chapters
  docs/03-components/05-input/checkbox.md
  docs/03-components/05-input/inputfield.md
  docs/03-components/05-input/inputfile.md
  docs/03-components/05-input/radio.md
  docs/03-components/05-input/select.md
  docs/03-components/05-input/textarea.md
  docs/readme.md
  ui/src/test/kotlin/kiwi/orbit/compose/ui/controls/CheckboxTest.kt
  ui/src/test/kotlin/kiwi/orbit/compose/ui/controls/RadioTest.kt
  ui/src/test/kotlin/kiwi/orbit/compose/ui/controls/SelectTest.kt
Labels: documentation

#486 Add `ScrollableTabRow` component
  docs/03-components/02-structure/tabs.mdx
  lint/src/main/kotlin/kiwi/orbit/compose/lint/detectors/MaterialDesignInsteadOrbitDesignDetector.kt
  ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/Tabs.kt
  ui/src/androidUnitTest/kotlin/kiwi/orbit/compose/ui/controls/TabsTest.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_tabs.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_tabs_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_tabs_dark.png
Labels: feature, new component

#485 Kotlin 1.9
  build.gradle.kts
  catalog/build.gradle.kts
  generator/src/main/java/kiwi/orbit/compose/generator/colors/ColorsGenerator.kt
  gradle.properties
  gradle/libs.versions.toml
  icons/build.gradle.kts
  illustrations/build.gradle.kts
  ui/build.gradle.kts
  ui/src/androidUnitTest/kotlin/kiwi/orbit/compose/ui/controls/CheckboxTest.kt
  ui/src/androidUnitTest/kotlin/kiwi/orbit/compose/ui/controls/RadioTest.kt
  ui/src/androidUnitTest/kotlin/kiwi/orbit/compose/ui/controls/SelectTest.kt
Labels: chore
