Repository kiwicom/orbit-compose, pull requests merged in 2023-11, with the labels that each got.

#575 Rework drawing expanded border
  ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/Checkbox.kt
  ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/Coupon.kt
  ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/SegmentedSwitch.kt
  ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/TextField.kt
  ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/utils/DrawScopeExtensions.kt
  ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/utils/ExpandedCornerSize.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_checkbox.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_checkboxField.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_checkboxField_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_checkboxField_dark.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_checkbox_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_checkbox_dark.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_coupon.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_coupon_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_coupon_dark.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_segmentedSwitch.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_segmentedSwitch_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_segmentedSwitch_dark.png
Labels: bug, chore

#580 Add `IconName` and `IllustrationName` enums
  catalog/build.gradle.kts
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/IconsScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/IllustrationsScreen.kt
  catalog/src/release/generated/baselineProfiles/baseline-prof.txt
  generator/src/main/java/kiwi/orbit/compose/generator/icons/IconsGenerator.kt
  generator/src/main/java/kiwi/orbit/compose/generator/illustrations/IllustrationsGenerator.kt
  icons/src/androidMain/baseline-prof.txt
  icons/src/androidMain/kotlin/kiwi/orbit/compose/icons/ColoredIconName.kt
  icons/src/androidMain/kotlin/kiwi/orbit/compose/icons/IconName.kt
  illustrations/src/androidMain/baseline-prof.txt
  illustrations/src/androidMain/kotlin/kiwi/orbit/compose/illustrations/IllustrationName.kt
  ui/src/androidMain/baseline-prof.txt
Labels: feature

#581 Use TimeSource's marker for time measuring in Toast (BC break)
  ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/Toast.kt
  ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/ToastHost.kt
Labels: chore
