Repository kiwicom/orbit-compose, pull requests merged in 2023-01, with the labels that each got.

#305 Fix `BadgeListItemNeutral`'s icon tint color to be InkNormal
  ui/src/main/java/kiwi/orbit/compose/ui/controls/BadgeList.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_badgeList.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_badgeList_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_badgeList_dark.png
Labels: bug, semver:patch

#309 Use SwipeableV2 in `Switch`
  ui/build.gradle.kts
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Switch.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/internal/SwipeableV2.kt
Labels: chore

#306 Add documentation for Alert, Badge, BadgeList, Button
  .github/workflows/build-ui-tests.yml
  .idea/dictionaries/shared.xml
  .idea/inspectionProfiles/Project_Default.xml
  component-status.yaml
  contributing.md
  docs/03-components/01-action/button.mdx
  docs/03-components/03-information/alert.mdx
  docs/03-components/03-information/badge.mdx
  docs/03-components/03-information/badgelist.mdx
  docs/03-components/15-primitives/badgeprimitive.mdx
  docs/03-components/15-primitives/buttonprimitive.mdx
  ui/build.gradle.kts
  ui/src/androidTest/kotlin/AlertTest.kt
  ui/src/androidTest/kotlin/BadgeListTest.kt
  ui/src/androidTest/kotlin/BadgeTest.kt
  ui/src/androidTest/kotlin/ButtonTest.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/BadgeList.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Button.kt
Labels: documentation, chore

#312 switch UI tests from emulator to robolectric
  .github/workflows/build-ui-tests.yml
  .github/workflows/build.yml
  gradle/libs.versions.toml
  ui/build.gradle.kts
  ui/src/test/kotlin/kiwi/orbit/compose/ui/ScreenshotTest.kt
  ui/src/test/kotlin/kiwi/orbit/compose/ui/controls/AlertTest.kt
  ui/src/test/kotlin/kiwi/orbit/compose/ui/controls/BadgeListTest.kt
  ui/src/test/kotlin/kiwi/orbit/compose/ui/controls/BadgeTest.kt
  ui/src/test/kotlin/kiwi/orbit/compose/ui/controls/ButtonTest.kt
Labels: skip-changelog

#313 Migrate to Material 3
  .idea/inspectionProfiles/Project_Default.xml
  .idea/scopes/ComposeMaterial3.xml
  .idea/scopes/scope_settings.xml
  catalog/build.gradle.kts
  catalog/src/main/java/kiwi/orbit/compose/catalog/CatalogApplication.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/Destinations.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/AlertScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ButtonScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/CheckboxScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ChoiceTileScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/DialogsMaterialDialog.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/DialogsScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/LinearProgressIndicatorScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ListChoiceScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/PillButtonScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/RadioScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/SeatScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/SegmentedSwitchScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/SelectFieldScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/StepperScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/SurfaceCardScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/SwitchScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TabsScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TagScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TextFieldScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TimelineScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TopAppBarScreensLarge.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TopAppBarScreensNormal.kt
  component-status.yaml
  contributing.md
  docs/02-foundation/04-color/theming.mdx
  docs/03-components/02-structure/tabs.mdx
  gradle/libs.versions.toml
  lint/src/main/kotlin/kiwi/orbit/compose/lint/detectors/MaterialDesignInsteadOrbitDesignDetector.kt
  lint/src/test/kotlin/kiwi/orbit/compose/lint/detectors/MaterialDesignInsteadOrbitDesignDetectorTest.kt
  readme.md
  ui/build.gradle.kts
  ui/src/main/java/kiwi/orbit/compose/ui/OrbitTheme.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/LinearProgressIndicator.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/SelectField.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Surface.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Tabs.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/Colors.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/ContentColor.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/Shapes.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/TextStyle.kt
  ui/src/main/java/kiwi/orbit/compose/ui/foundation/Typography.kt
  ui/src/test/kotlin/kiwi/orbit/compose/ui/ScreenshotTest.kt
  ui/src/test/kotlin/kiwi/orbit/compose/ui/controls/TabsTest.kt
Labels: feature

#316 Set TopAppBar icons' size to 24.sp
  ui/src/main/java/kiwi/orbit/compose/ui/controls/TopAppBar.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_topAppBar.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_topAppBarLarge.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_topAppBarLarge_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_topAppBarLarge_dark.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_topAppBar_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_topAppBar_dark.png
Labels: bug

#318 Moved TopAppBar navigation icons to :icons module
  generator/src/main/java/kiwi/orbit/compose/generator/icons/IconsGenerator.kt
  icons/src/main/java/kiwi/orbit/compose/icons/TopAppBarIcons.kt
  icons/src/main/res/drawable/ic_top_app_bar_back.xml
  icons/src/main/res/drawable/ic_top_app_bar_close.xml
  ui/src/main/java/kiwi/orbit/compose/ui/controls/TopAppBar.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/TopAppBarLarge.kt
  ui/src/main/res/drawable/ic_appbar_arrow_right.xml
  ui/src/main/res/values-ldrtl/drawables.xml
  ui/src/main/res/values/drawables.xml
Labels: feature

#320 fix crash when lineHeight is not defined in sp
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Icon.kt
Labels: bug

#319 Add `Tile` component
  .idea/codeStyles/Project.xml
  catalog/src/main/java/kiwi/orbit/compose/catalog/CatalogApplication.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/Destinations.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TileScreen.kt
  component-status.yaml
  docs/03-components/02-structure/tile.mdx
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Tile.kt
  ui/src/test/kotlin/kiwi/orbit/compose/ui/ScreenshotTest.kt
  ui/src/test/kotlin/kiwi/orbit/compose/ui/controls/TileTest.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_tile.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_tile_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_tile_dark.png
Labels: feature

#330 Add Divider, LocalTextStyle, LocalContentColor lint rules
  lint/src/main/kotlin/kiwi/orbit/compose/lint/detectors/MaterialDesignInsteadOrbitDesignDetector.kt
  lint/src/test/kotlin/kiwi/orbit/compose/lint/detectors/MaterialDesignInsteadOrbitDesignDetectorTest.kt
Labels: feature

#331 Fix m3 migration issues
  docs/02-foundation/04-color/theming.mdx
  ui/src/main/java/kiwi/orbit/compose/ui/controls/SelectField.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Tabs.kt
  ui/src/main/java/kiwi/orbit/compose/ui/controls/internal/OrbitElevations.kt
Labels: bug, skip-changelog

#332 Add `Card` component
  catalog/src/main/java/kiwi/orbit/compose/catalog/CatalogApplication.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/Destinations.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/CardScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ListChoiceScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ListScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TileScreen.kt
  catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TimelineScreen.kt
  component-status.yaml
  docs/03-components/02-structure/card.mdx
  ui/src/main/java/kiwi/orbit/compose/ui/controls/Card.kt
  ui/src/test/kotlin/kiwi/orbit/compose/ui/ScreenshotTest.kt
  ui/src/test/kotlin/kiwi/orbit/compose/ui/controls/CardTest.kt
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_card.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_card_big.png
  ui/src/test/snapshots/images/kiwi.orbit.compose.ui_ScreenshotTest_card_dark.png
Labels: feature, new component
